version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: carrierwave
    versions:
    - 2.1.1
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
  - dependency-name: mini_racer
    versions:
    - 0.3.1
